import { execSync } from 'child_process';
import type { TriagedFindings, Finding } from './triage.js';

function findingToMarkdown(f: Finding): string {
  const location = f.line !== null ? `${f.file}:${f.line}` : f.file;
  // Only annotate provenance when it carries signal — i.e., consensus from
  // ≥2 sources. Single-source findings would just add noise.
  const consensus =
    f.mergedFrom && f.mergedFrom.length > 1
      ? ` _(found by ${f.mergedFrom.length} sources: ${f.mergedFrom.join(', ')})_`
      : '';
  return `- **[${f.severity}]** \`${location}\` — ${f.description}${consensus}`;
}

// Coverage status surfaced in the comment so partial runs never read as
// full coverage (Rule 12). All fields optional/defaulted for back-compat.
export interface ReviewCoverage {
  // Reviewers selected before failures/truncation.
  plannedReviewerCount?: number;
  // Reviewer (or reviewer@model) labels that errored/timed out.
  degraded?: string[];
  // Reviewers dropped by the maxAgents cap.
  skipped?: string[];
  // Findings kept but not revalidated due to the revalidation budget.
  unverifiedCount?: number;
  // False positives dropped by the revalidation pass.
  droppedCount?: number;
}

export function formatPRComment(
  triaged: TriagedFindings,
  reviewerCount: number,
  coverage: ReviewCoverage = {}
): string {
  const totalCount =
    triaged.critical.length +
    triaged.high.length +
    triaged.medium.length +
    triaged.low.length +
    triaged.nitpick.length;

  const lines: string[] = [];

  lines.push('## Claude Flow Review');
  lines.push('');
  const planned = coverage.plannedReviewerCount ?? reviewerCount;
  const reviewerSummary =
    planned > reviewerCount
      ? `${reviewerCount} of ${planned} reviewer${planned !== 1 ? 's' : ''}`
      : `${reviewerCount} reviewer${reviewerCount !== 1 ? 's' : ''}`;
  lines.push(
    `Found **${totalCount} finding${totalCount !== 1 ? 's' : ''}** across ${reviewerSummary}.`
  );
  lines.push('');

  // Partial-coverage banner — only when something was degraded/skipped/unverified.
  const coverageNotes: string[] = [];
  if (coverage.degraded && coverage.degraded.length > 0) {
    coverageNotes.push(`${coverage.degraded.length} reviewer call(s) degraded: ${coverage.degraded.join(', ')}`);
  }
  if (coverage.skipped && coverage.skipped.length > 0) {
    coverageNotes.push(`${coverage.skipped.length} reviewer(s) skipped (agent cap): ${coverage.skipped.join(', ')}`);
  }
  if (coverage.unverifiedCount && coverage.unverifiedCount > 0) {
    coverageNotes.push(`${coverage.unverifiedCount} finding(s) kept but unverified (revalidation budget)`);
  }
  if (coverage.droppedCount && coverage.droppedCount > 0) {
    coverageNotes.push(`${coverage.droppedCount} finding(s) dropped as false positives by revalidation`);
  }
  if (coverageNotes.length > 0) {
    lines.push('> ⚠️ **Partial coverage** — ' + coverageNotes.join('; ') + '.');
    lines.push('');
  }

  // CRITICAL
  if (triaged.critical.length > 0) {
    lines.push('### Critical Issues');
    lines.push('');
    for (const f of triaged.critical) {
      lines.push(findingToMarkdown(f));
    }
    lines.push('');
  }

  // HIGH
  if (triaged.high.length > 0) {
    lines.push('### High Severity');
    lines.push('');
    for (const f of triaged.high) {
      lines.push(findingToMarkdown(f));
    }
    lines.push('');
  }

  // MEDIUM
  if (triaged.medium.length > 0) {
    lines.push('### Medium Severity');
    lines.push('');
    for (const f of triaged.medium) {
      lines.push(findingToMarkdown(f));
    }
    lines.push('');
  }

  // LOW + NITPICK in collapsed block
  const minorFindings = [...triaged.low, ...triaged.nitpick];
  if (minorFindings.length > 0) {
    lines.push(
      `<details><summary>Minor findings (${minorFindings.length})</summary>`
    );
    lines.push('');
    for (const f of minorFindings) {
      lines.push(findingToMarkdown(f));
    }
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by claude-flow PR reviewer_');

  return lines.join('\n');
}

export async function postToGitHub(
  prNumber: number,
  comment: string,
  hasCritical: boolean
): Promise<void> {
  if (!process.env.GITHUB_TOKEN) {
    throw new Error('GITHUB_TOKEN environment variable is required');
  }

  // Escape the comment for shell usage via a temp file approach to avoid
  // argument injection issues with arbitrary comment content.
  const escaped = comment.replace(/'/g, `'\\''`);

  let cmd: string;
  if (hasCritical) {
    cmd = `gh pr review ${prNumber} --request-changes --body '${escaped}'`;
  } else {
    cmd = `gh pr comment ${prNumber} --body '${escaped}'`;
  }

  execSync(cmd, { stdio: 'inherit' });
}
