import { execSync } from 'child_process';
import type { TriagedFindings, Finding } from './triage.js';

function findingToMarkdown(f: Finding): string {
  const location = f.line !== null ? `${f.file}:${f.line}` : f.file;
  // Only annotate provenance when it carries signal — i.e., consensus from
  // ≥2 sources. Single-source findings would just add noise.
  const consensus =
    f.mergedFrom && f.mergedFrom.length > 1
      ? ` _(found by ${f.mergedFrom.length} sources: ${f.mergedFrom.join(', ')})_`
      : '';
  return `- **[${f.severity}]** \`${location}\` — ${f.description}${consensus}`;
}

export function formatPRComment(
  triaged: TriagedFindings,
  reviewerCount: number
): string {
  const totalCount =
    triaged.critical.length +
    triaged.high.length +
    triaged.medium.length +
    triaged.low.length +
    triaged.nitpick.length;

  const lines: string[] = [];

  lines.push('## Claude Flow Review');
  lines.push('');
  lines.push(
    `Found **${totalCount} finding${totalCount !== 1 ? 's' : ''}** across ${reviewerCount} reviewer${reviewerCount !== 1 ? 's' : ''}.`
  );
  lines.push('');

  // CRITICAL
  if (triaged.critical.length > 0) {
    lines.push('### Critical Issues');
    lines.push('');
    for (const f of triaged.critical) {
      lines.push(findingToMarkdown(f));
    }
    lines.push('');
  }

  // HIGH
  if (triaged.high.length > 0) {
    lines.push('### High Severity');
    lines.push('');
    for (const f of triaged.high) {
      lines.push(findingToMarkdown(f));
    }
    lines.push('');
  }

  // MEDIUM
  if (triaged.medium.length > 0) {
    lines.push('### Medium Severity');
    lines.push('');
    for (const f of triaged.medium) {
      lines.push(findingToMarkdown(f));
    }
    lines.push('');
  }

  // LOW + NITPICK in collapsed block
  const minorFindings = [...triaged.low, ...triaged.nitpick];
  if (minorFindings.length > 0) {
    lines.push(
      `<details><summary>Minor findings (${minorFindings.length})</summary>`
    );
    lines.push('');
    for (const f of minorFindings) {
      lines.push(findingToMarkdown(f));
    }
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by claude-flow PR reviewer_');

  return lines.join('\n');
}

export async function postToGitHub(
  prNumber: number,
  comment: string,
  hasCritical: boolean
): Promise<void> {
  if (!process.env.GITHUB_TOKEN) {
    throw new Error('GITHUB_TOKEN environment variable is required');
  }

  // Escape the comment for shell usage via a temp file approach to avoid
  // argument injection issues with arbitrary comment content.
  const escaped = comment.replace(/'/g, `'\\''`);

  let cmd: string;
  if (hasCritical) {
    cmd = `gh pr review ${prNumber} --request-changes --body '${escaped}'`;
  } else {
    cmd = `gh pr comment ${prNumber} --body '${escaped}'`;
  }

  execSync(cmd, { stdio: 'inherit' });
}
